org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.log.com.tuandev.fbsbarcode=debug
org.slf4j.simpleLogger.log.okhttp3=warn
org.slf4j.simpleLogger.log.org.apache.pdfbox=warn
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss
